config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'rooms#index'

  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    validates :content, presence: true
    after_create_commit { MessageBroadcastJob.perform_later self }
    belongs_to :user
    belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    validates :name,:presence=>true,:length=>{:maximum=>30}
    has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  def email_required?
    false
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name,:presence=>true,:length=>{:maximum=>20}
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = Room.all.order(:id)
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)
    @room.save
    redirect_to root_path
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_header.html.erb
<% if !current_user.nil? %>       
  <header class="navbar navbar-fixed-top navbar-inverse fixed-top" style="background: rgba(255,255,255,0.8);">
    <a class="bolder">ログインユーザー: <%= current_user.name %><a>
    <ul class="nav pull-right nav-pills"　style="background-color:#000066;"> 
      <li class="bolder"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Real Time Chat For Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/animejs@3.0.1/lib/anime.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if content_for?(:body_attributes) %>
      <%= yield(:body_attributes) %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <p><%= "#{message.user.name} : #{message.created_at.to_s(:without_second)}" %></p>
  <div class ="text">
    <p><%= "#{message.content}" %></p>
    <%= javascript_pack_tag 'messages' %>
  </div>
</div>

app/views/rooms/index.html.erb
<body class="subroom">
  <div class="row bolder textcolor">
    <div class="col-md-6 align-self-center color center">
      <h1 class="container footercenter">
      <i class="fa fa-fire"></i> <i class="fa fa-soccer-ball-o"></i>
      MATCH DAY 
      <i class="fa fa-soccer-ball-o"></i> <i class="fa fa-fire"></i>
      </h1>
      <ul></br>
        <% @rooms.first(3).each do |room| %>
          <div data-turbolinks="false">
            <li class="list"><%= link_to room.name, room_path(room) %></li>
          </div>
        <% end %>
      </ul></br>
      <div class="footercenter">
      <h8>新規トークルームはコチラ(※空白、30文字以上NG) </h8></br></br>
      <%= form_with model: @room do |f| %>
        <%= f.label :Roomname%>
        <%= f.text_field :name, :size=>"40" %></br></br>
        <%= f.submit class:"btn btn-primary " %>
      <% end %></br>
      </div>
      <ul>
      <% if !Room.find_by(id: 4).nil? %>  
        <% @rooms[3..9999].each do |room| %>
          <div data-turbolinks="false">
          <li class="list"><%= link_to room.name, room_path(room) %></li>
          </div>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
</body>

app/views/rooms/show.html.erb
<% if @room.id==1 %> 
  <body class="mainroom1">
  <% elsif  @room.id==2 %>
  <body class="mainroom2">
  <% elsif  @room.id==3 %>
  <body class="mainroom3">
  <% else %>
  <body class="subroom">
<% end %>
  <div class="row bolder textcolor">
    <div class="col-md-8 align-self-center color center">
      <h4 class="container bolder footercenter"><%= @room.name %></h1></br>
      <div id="messages" data-room_id="<%= @room.id %>">
        <%= render @messages %>
      </div>
    </div>
  </div></br></br>
  <footer class="footer fixed-bottom" style="background: rgba(255,255,255,0.8);">
    <div class="footercenter">
      <%= label nil, nil, 'Enterキーを押してね！(※空白NG)　' %>
      <%= text_field nil, nil, 'data-behavior': 'room_speaker', :size => "150" %>
    </div>
  </footer>
</body> 